In [1]:
import pandas as pd
import numpy as np
from usfull_tools import load_DS
#from catboost import Pool, CatBoostRegressor, CatBoostClassifier
#from sklearn.model_selection import train_test_split, cross_val_score
pd.options.display.max_columns = None
%matplotlib inline

from set_vars import KAGGLE_PREFIX, debug_mode, KAGGLE_DIR, target_column, target_type, id_column

train, test = load_DS(debug_mode, KAGGLE_DIR, KAGGLE_PREFIX, '_prepare.csv')
del train

cols = pd.read_csv(KAGGLE_DIR + KAGGLE_PREFIX + '_important_columns.csv')
test = test[cols['Feature']]
test.shape

(1459, 129)

In [2]:
import pickle

with open(KAGGLE_DIR + KAGGLE_PREFIX + 'classifier.pkl', 'rb') as fid:
    model = pickle.load(fid)

y_test = model.predict(test)
predict = pd.read_csv(KAGGLE_DIR + KAGGLE_PREFIX + 'test.csv', usecols=[id_column])
predict[target_column] = y_test.astype(np.int)
predict.to_csv(KAGGLE_DIR + KAGGLE_PREFIX + 'submission.csv', index=False, sep=',')

In [3]:
predict

        Id  SalePrice
0     1461     136150
1     1462     148029
2     1463     178141
3     1464     182012
4     1465     229389
5     1466     186877
6     1467     181031
7     1468     169460
8     1469     156689
9     1470     130971
10    1471     180146
11    1472     150195
12    1473     110170
13    1474     155266
14    1475     134072
15    1476     327562
16    1477     233468
17    1478     217372
18    1479     280541
19    1480     326481
20    1481     304191
21    1482     169825
22    1483     186748
23    1484     179212
24    1485     182563
25    1486     227973
26    1487     294382
27    1488     265607
28    1489     202768
29    1490     168951
...    ...        ...
1429  2890     108566
1430  2891     143412
1431  2892      90473
1432  2893      74452
1433  2894      76668
1434  2895     277164
1435  2896     238468
1436  2897     180167
1437  2898     191475
1438  2899     218826
1439  2900     139476
1440  2901     199063
1441  2902     164534
1442  2903     312064
1443  2904     250652
1444  2905     121038
1445  2906     151776
1446  2907     140155
1447  2908     161095
1448  2909     116137
1449  2910      78654
1450  2911      79227
1451  2912     189473
1452  2913     100862
1453  2914      94962
1454  2915     119177
1455  2916     102036
1456  2917     166497
1457  2918     131482
1458  2919     208858

[1459 rows x 2 columns]